update deployment scripts

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,25 +1,28 @@
 #!/bin/sh
 
 branch="$(git rev-parse --abbrev-ref HEAD)"
+email="$(git config user.email)"
 
-if [ "$branch" = "master" ]; then
-  echo "You can't commit directly to master branch"
-  exit 1
-fi
+if [[ "$email" != "ehi.akhile@gmail.com" ]]; then
+  if [ "$branch" = "master" ]; then
+    echo "You can't commit directly to master branch"
+    exit 1
+  fi
 
-if [ "$branch" = "main" ]; then
-  echo "You can't commit directly to main branch"
-  exit 1
-fi
+  if [ "$branch" = "main" ]; then
+    echo "You can't commit directly to main branch"
+    exit 1
+  fi
 
-if [ "$branch" = "development" ]; then
-  echo "You can't commit directly to development branch"
-  exit 1
-fi
+  if [ "$branch" = "development" ]; then
+    echo "You can't commit directly to development branch"
+    exit 1
+  fi
 
-if [ "$branch" = "develop" ]; then
-  echo "You can't commit directly to develop branch"
-  exit 1
+  if [ "$branch" = "develop" ]; then
+    echo "You can't commit directly to develop branch"
+    exit 1
+  fi
 fi
 
 echo "\t\033[41m*****You should have been running unit tests now!******\033[0m";
