prevent commiting directly to master and development branches

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,5 +1,27 @@
 #!/bin/sh
 
+branch="$(git rev-parse --abbrev-ref HEAD)"
+
+if [ "$branch" = "master" ]; then
+  echo "You can't commit directly to master branch"
+  exit 1
+fi
+
+if [ "$branch" = "main" ]; then
+  echo "You can't commit directly to main branch"
+  exit 1
+fi
+
+if [ "$branch" = "development" ]; then
+  echo "You can't commit directly to development branch"
+  exit 1
+fi
+
+if [ "$branch" = "develop" ]; then
+  echo "You can't commit directly to develop branch"
+  exit 1
+fi
+
 echo "\t\033[41m*****You should have been running unit tests now!******\033[0m";
 echo "\n\n\n"
 
